### ISSUE TITLE
See if we can extend the existing prow trigger plugin to cover our use case.

### ISSUE THREAD

**Issue by krasi-georgiev** [prometheus/prombench#50]
At the moment we have the benchmarking plugin to trigger benchmarks from comments.
Because of this we need to fork Prow and rebuild the Prow images that are deployed on k8s.

If we can modify the existing trigger plugin to cover our use case and it is accepted upstream than we wouldn't need the Prow fork.

**Comment by geekodour** [comment]
I opened a PR to k8s/test-infra https://github.com/kubernetes/test-infra/pull/13098 but the changes were not accepted due to how the `trigger` plugin is used by some other components of prow. 

for now, I think using the external prow plugin/ `benchmark.go` plugin is the way to go. either way the shift to github actions will remove this usecase for us.

**Comment by krasi-georgiev** [comment]
Yes will close once we migrate everything to github actions.
